parameters:
  name: 'anthony'
services:
  _defaults:
    autowire: true
    autoconfigure: true
  Simly\Controller\SimlyController:
    arguments:
      - '@doctrine.orm.simly_entity_manager'

#  Simly\Controller\SimlyController: ~

