doctrine:
    dbal:
        # wrapper_class: App\Doctrine\DynamicConnection
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            Shopify:
                url: '%env(resolve:SHOPIFY_DATABASE_URL)%'
            loto:
                url: '%env(resolve:LOTO_DATABASE_URL)%'
            alfa:
                url: '%env(resolve:ALFA_DATABASE_URL)%'
            touch:
                url: '%env(resolve:TOUCH_DATABASE_URL)%'
            ogero:
                url: '%env(resolve:OGERO_DATABASE_URL)%'
            estore:
                url: '%env(resolve:ESTORE_DATABASE_URL)%'
            notification:
                url: '%env(resolve:NOTIFICATION_DATABASE_URL)%'
            iveri:
                url: '%env(resolve:IVERI_DATABASE_URL)%'
        default_connection: default
        # charset: UTF8
        # logging: true
        # profiling: false
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
                        NOW: DoctrineExtensions\Query\Mysql\Now
                        DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                        FROM_UNIXTIME: DoctrineExtensions\Query\Mysql\FromUnixtime
                        JSON_CONTAINS: DoctrineExtensions\Query\Mysql\JsonContains
                    string_functions:
                        MATCH: DoctrineExtensions\Query\Mysql\MatchAgainst
                        GREATEST: DoctrineExtensions\Query\Mysql\Greatest
                        COLLATE: DoctrineExtensions\Query\Mysql\Collate
            Shopify:
                connection: Shopify
                mappings:
                    Shopify:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Shopify'
                        prefix: 'App\Entity\Shopify'
                        alias: Shopify
            loto:
                connection: loto
                mappings:
                    Loto:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Loto'
                        prefix: 'App\Entity\Loto'
                        alias: Loto
            touch:
                connection: touch
                mappings:
                    Touch:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Touch'
                        prefix: 'App\Entity\Touch'
                        alias: Touch
            alfa:
                connection: alfa
                mappings:
                    Alfa:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Alfa'
                        prefix: 'App\Entity\Alfa'
                        alias: Alfa
            ogero:
                connection: ogero
                mappings:
                    Ogero:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Ogero'
                        prefix: 'App\Entity\Ogero'
                        alias: Ogero
            estore:
                connection: estore
                mappings:
                    Estore:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Estore'
                        prefix: 'App\Entity\Estore'
                        alias: Estore
            notification:
                connection: notification
                mappings:
                    Notification:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Notification'
                        prefix: 'App\Entity\Notification'
                        alias: Notification
            iveri:
                connection: iveri
                mappings:
                    Notification:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Iveri'
                        prefix: 'App\Entity\Iveri'
                        alias: iveri
            

