doctrine:
    dbal:
        # wrapper_class: App\Doctrine\DynamicConnection
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            Shopify:
                url: '%env(resolve:SHOPIFY_DATABASE_URL)%'
            loto:
                url: '%env(resolve:LOTO_DATABASE_URL)%'
            alfa:
                url: '%env(resolve:ALFA_DATABASE_URL)%'
            touch:
                url: '%env(resolve:TOUCH_DATABASE_URL)%'
            ogero:
                url: '%env(resolve:OGERO_DATABASE_URL)%'
            estore:
                url: '%env(resolve:ESTORE_DATABASE_URL)%'
            notification:
                url: '%env(resolve:NOTIFICATION_DATABASE_URL)%'
            topup:
                url: '%env(resolve:TOPUP_DATABASE_URL)%'
            terranet:
                url: '%env(resolve:TERRANET_DATABASE_URL)%'
            invoices:
                url: '%env(resolve:INVOICES_DATABASE_URL)%'
            sodetel:
                url: '%env(resolve:SODETEL_DATABASE_URL)%'
            gift2games:
                url: '%env(resolve:GIFT2GAMES_DATABASE_URL)%'
            windsl:
                url: '%env(resolve:WINDSL_DATABASE_URL)%'
            simly:
                url: '%env(resolve:SIMLY_DATABASE_URL)%'

        default_connection: default
        # charset: UTF8
        # logging: true
        # profiling: false
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
                        NOW: DoctrineExtensions\Query\Mysql\Now
                        DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                        FROM_UNIXTIME: DoctrineExtensions\Query\Mysql\FromUnixtime
                        JSON_CONTAINS: DoctrineExtensions\Query\Mysql\JsonContains
                    string_functions:
                        MATCH: DoctrineExtensions\Query\Mysql\MatchAgainst
                        GREATEST: DoctrineExtensions\Query\Mysql\Greatest
                        COLLATE: DoctrineExtensions\Query\Mysql\Collate
            Shopify:
                connection: Shopify
                mappings:
                    Shopify:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Shopify'
                        prefix: 'App\Entity\Shopify'
                        alias: Shopify
            loto:
                connection: loto
                mappings:
                    Loto:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Loto'
                        prefix: 'App\Entity\Loto'
                        alias: Loto
            touch:
                connection: touch
                mappings:
                    Touch:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Touch'
                        prefix: 'App\Entity\Touch'
                        alias: Touch
            alfa:
                connection: alfa
                mappings:
                    Alfa:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Alfa'
                        prefix: 'App\Entity\Alfa'
                        alias: Alfa
            ogero:
                connection: ogero
                mappings:
                    Ogero:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Ogero'
                        prefix: 'App\Entity\Ogero'
                        alias: Ogero
            estore:
                connection: estore
                mappings:
                    Estore:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Estore'
                        prefix: 'App\Entity\Estore'
                        alias: Estore
            notification:
                connection: notification
                mappings:
                    Notification:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Notification'
                        prefix: 'App\Entity\Notification'
                        alias: Notification
            topup:
                connection: topup
                mappings:
                    Notification:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/topup'
                        prefix: 'App\Entity\topup'
                        alias: topup
            terranet:
                connection: terranet
                mappings:
                    Terranet:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/TerraNet'
                        prefix: 'App\Entity\TerraNet'
                        alias: TerraNet
            sodetel:
                connection: sodetel
                mappings:
                    Sodetel:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Sodetel'
                        prefix: 'App\Entity\Sodetel'
                        alias: Sodetel

            gift2games:
                connection: gift2games
                mappings:
                    Gift2Games:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Gift2Games'
                        prefix: 'App\Entity\Gift2Games'
                        alias: Gift2Games

            invoices:
                connection: invoices
                mappings:
                    Notification:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Invoices'
                        prefix: 'App\Entity\Invoices'
                        alias: invoices
            windsl:
                connection: windsl
                mappings:
                    windsl:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Windsl'
                        prefix: 'App\Entity\Windsl'
                        alias: windsl

            simly:
                connection: simly
                mappings:
                    Simly:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Simly'
                        prefix: 'App\Entity\Simly'
                        alias: Simly
