scheb_two_factor:

  # Email authentication config
  email:
    enabled: true                  # If email authentication should be enabled, default false
    mailer: scheb_two_factor.security.email.symfony_auth_code_mailer      # Use alternative service to send the authentication code
    sender_email: donotreply@suyool.com   # Sender email address
    sender_name: Suyool         # Sender name
    digits: 6                      # Number of digits in authentication code
    template: "Admin/security/authentication.html.twig"   # Template used to render the authentication form

  # The service which is used to persist data in the user object. By default Doctrine is used. If your entity is
  # managed by something else (e.g. an API), you have to implement a custom persister
  persister: scheb_two_factor.persister.doctrine

  # If your Doctrine user object is managed by a model manager, which is not the default one, you have to
  # set this option. Name of entity manager or null, which uses the default one.
  model_manager_name: ~

  
  ip_whitelist:
    - 127.0.0.1


  # The security token classes, which trigger two-factor authentication.
  # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
  # two-factor authentication for other authentication methods, add their security token classes.
  security_tokens:
    #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken