security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout   # The logout route name

    access_control:
        #- { path: ^/admin_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/dashadmin, roles: ROLE_ADMIN }
