security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout   # The logout route name
                target: /admin_login           
            two_factor:
                auth_form_path: /2fa                  # Path or route name of the two-factor form
                check_path: /2fa_check                # Path or route name of the two-factor code check
                default_target_path: /                # Where to redirect by default after successful authentication

    access_control:
        - { path: ^/admin_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/alfa , roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/touch , roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/users , roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/sendAuthCode, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        
    
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN]
