twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        # production_url: '%production_url%'
        app_name: '%app.name%'
        base_url: '%router.request_context.base_url%'
    paths:
        '%kernel.project_dir%/bundles/Simly/Resources/views': SimlyBundle