monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - Users
        - Winning
    handlers:
        users:
            type: stream
            path: "%kernel.logs_dir%/users.log"
            level: debug
            channels: ['Users']
        winning:
            type: stream
            path: "%kernel.logs_dir%/winning.log"
            level: debug
            channels: ['Winning']
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        
            # formatter: app.session_request_formatter
