monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: critical
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        users:
            type: stream
            path: "%kernel.logs_dir%/Users.log"
            level: debug
            channels: ['Users']
        winning:
            type: stream
            path: "%kernel.logs_dir%/winning.log"
            level: debug
            channels: ['Winning']
