#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
  controller: App\Controller\Admin\DashboardController::index
  path: /dashadmin

# admin_loto_orders:
#   resource: 'App\Controller\Admin\lotoAdminController'
#   prefix: /dashadmin


2fa_login:
  path: /2fa
  defaults:
    # "scheb_two_factor.form_controller" references the controller service provided by the bundle.
    # You don't HAVE to use it, but - except you have very special requirements - it is recommended.
    _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
  path: /2fa_check


logout:
  path: /admin/logout

logout_user:
  path: /logout

app_payment:
  path: /{code}
  controller: App\Controller\PaymentController::index
  requirements:
    code: '^(?:(P|p)[A-Za-z0-9]*)$' 

invitation_card:
  path: '/{code}'
  controller: 'App\Controller\InvitationCardController::index'
  requirements:
    code: '^I(?:[A-Za-z0-9]*)$'

app_request:
  path: /{code}
  controller: App\Controller\RTPController::index
  requirements:
    code: '^(?:(R)[A-Za-z0-9]*)$'

app_requesttopay:
  path: /requestToPay
  controller: App\Controller\IveriController::requestToPay

bundle_test:
  path: /TestUnit
  controller: TestUnit\Controller\DefaultController::index
simly:
  path: /simly
  controller: TestUnit\Controller\SimlyController::index

