# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ar
    router.request_context.host: '%env(SITE_BASE_SCHEME)%'
    router.request_context.scheme: '%env(SITE_BASE_HOST)%'
    router.request_context.base_url: '%env(SITE_BASE_URL)%'
    asset.request_context.base_path: '%router.request_context.base_url%'
    asset.request_context.secure: '%env(SITE_SECURE)%'
    google_recaptcha_site_key: '6LdFtHgnAAAAABD55OKfi_bKEG3ktD8cAKwyUfOx'
    hash_algo: 'sha512'
    certificate: '%env(CERTIFICATE)%'
    LOTO_MERCHANT_ID: '1'
    ALFA_POSTPAID_MERCHANT_ID: '2'
    ALFA_PREPAID_MERCHANT_ID: '3'
    TOUCH_POSTPAID_MERCHANT_ID: '4'
    TOUCH_PREPAID_MERCHANT_ID: '5'
    OGERO_MERCHANT_ID: '6'
    TERRANET_MERCHANT_ID: '7'
    SODETEL_POSTPAID_MERCHANT_ID: '8'
    SODETEL_4G_MERCHANT_ID: '9'
    GIFT2GAMES_MERCHANT_ID: '9'
    CURRENCY_LBP: 'LBP'
    CURRENCY_USD: 'USD'
    METHOD_POST: 'POST'
    METHOD_GET: 'GET'
    CARDS_PER_DAY_PREPAID: 2
    # production_url: 'https://www.elnashra.com/'
    app.name: 'Suyool'

    base_url: '%router.request_context.base_url%'

services:
    App\Twig\AppExtension:
        arguments:
            $requestStack: '@request_stack'
        tags:
            - { name: 'twig.extension' }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $hash_algo: '%hash_algo%'
            $certificate: '%certificate%'
            # $LOTO_MERCHANT_ID: '1'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Form/'

    ReCaptcha\ReCaptcha:
        arguments:
            - '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # App\EventListener\SearchIndexer:
    #     tags:
    #         - { name: doctrine.event_listener, event: prePersist }
    #         - { name: doctrine.event_listener, event: preUpdate }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # App\EventListener\SearchIndexer:
    #     tags:
    #         - { name: doctrine.event_listener, event: prePersist }
    #         - { name: doctrine.event_listener, event: preUpdate }
    # App\EventListener\ControllerListener:
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.controller }
    #         - { name: kernel.event_listener, event: kernel.terminate }

    # App\EventListener\RequestSubscriber:
    #     arguments:
    #         $logger: '@monolog.logger.requestApi'

    App\Service\SuyoolServices:
        lazy: true
        arguments:
            $merchantAccountID: ''
            $cashin: '@monolog.logger.cashin'
            $cashout: '@monolog.logger.cashout'
            $winning: '@monolog.logger.Winning'
            $userlog: '@monolog.logger.Users'

    App\EventListener\DomainAccessListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    App\Service\NotificationServices:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Users' }

    App\Command\loto\winningTickets:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Winning' }
    
    App\Command\loto\PlayLoto:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Play' }

    App\Service\LotoServices:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Play' }

    App\Controller\LotoController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Loto' }
    
    App\Service\BobServices:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'BoB' }
    
    App\Controller\IveriController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Iveri' }

    App\Service\BobPaymentServices:
        lazy: true
        tags:
            - { 'name': 'monolog.logger', 'channel': 'topup' }

    App\Service\TerraNetService:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'terraNet' }

    App\Controller\TopupController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Iveri' }

    App\Service\SodetelService:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Sodetel' }

    App\Controller\Gift2GamesController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Users' }
    App\Controller\SodetelController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Users' }
    
    App\Controller\AlfaController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Alfa' }
    
    App\Controller\TerranetController:
        tags:
            - { 'name': 'monolog.logger', 'channel': 'Alfa' }
        

    # App\Controller\LotoController:
    #     arguments:
    #         $LOTO_MERCHANT_ID: '%LOTO_MERCHANT_ID%'
        
